/**
 * Re-export of all model types from the API's generated Prisma client.
 *
 * The actual model interfaces live in `humanupgradeapi/generated/models.ts`
 * and are regenerated by `prisma generate`.
 */
export * from '../../../humanupgradeapi/generated/models.js'
